import type { Metadata } from "next";
import "./globals.css";
import font from "next/font/local";


const myFont = font({
  src: '../app/fonts/GraphikRegular.otf',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></link></head>
      <body className={myFont.className}>
        {children}
      </body>
    </html>
  );
}
